name: Test CRC
on:
  push:
  workflow_dispatch:

jobs:
  launch-crc:
    name: Download and launch CRC
    # runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: redhat-actions/openshift-cli-installer@v1
        with:
          oc: latest
          crc: latest

      - name: Setup and run CRC
        shell: bash
        env:
          PULL_SECRET_FILE: .pull_secret
        run: |
          crc setup
          echo '${{ secrets.CRC_PULL_SECRET }}' > ${{ env.PULL_SECRET_FILE }}
          crc start --memory 6144 --pull-secret-file ${{ env.PULL_SECRET_FILE }}
          eval $(crc oc-env)

          # Extract the admin credentials from the line:
          # "To login as a cluster admin, run 'oc login -u kubeadmin -p <password> https://api.crc.testing:6443'. "
          export LOGIN_COMMAND=$(crc start | grep "kubeadmin" | awk -F"'" '{ print $2 }')
          $LOGIN_COMMAND
          eval

      # - name: Log in to CRC cluster
      #   uses: redhat-actions/oc-login@v1
      #   with:
      #     openshift_server_url: https://api.crc.testing:6443
      #     openshift_username: kubeadmin
      #     openshift_password: ${{ env.KUBEADMIN_PASSWORD }}
      #thub     insecure_skip_tls_verify: true

      - name: Run some oc commands
        run: |
          oc whoami
          oc project
