name: Test CRC
on:
  push:
  workflow_dispatch:

jobs:
  launch-crc:
    name: Download and launch CRC
    runs-on: macos-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ macos-latest, ubuntu-20.04 ]
    # runs-on: ${{ matrix.os }}

    steps:
      - uses: redhat-actions/openshift-cli-installer@v1
        with:
          oc: latest
          crc: latest

      - name: Clean environment
        run: |
          set -xeE -o pipefail
          crc delete -f || true
          crc cleanup || true
          # https://github.com/kubernetes/minikube/issues/6143
          rm -v /var/db/dhcpd_leases || true

      - name: Setup and run CRC
        shell: bash
        env:
          PULL_SECRET_FILE: .pull_secret
        run: |
          set -xeE -o pipefail

          crc setup
          echo '${{ secrets.CRC_PULL_SECRET }}' > ${{ env.PULL_SECRET_FILE }}
          crc start --pull-secret-file ${{ env.PULL_SECRET_FILE }} --log-level debug
          eval $(crc oc-env)

          # Extract the admin credentials from the single quotes in the line:
          # "To login as a cluster admin, run 'oc login -u kubeadmin -p <password> https://api.crc.testing:6443'. "
          $(crc start | grep "kubeadmin" | awk -F"'" '{ print $2 }') --insecure-skip-tls-verify

      # - name: Log in to CRC cluster
      #   uses: redhat-actions/oc-login@v1
      #   with:
      #     openshift_server_url: https://api.crc.testing:6443
      #     openshift_username: kubeadmin
      #     openshift_password: ${{ env.KUBEADMIN_PASSWORD }}
      #     insecure_skip_tls_verify: true

      - name: Run some oc commands
        run: |
          set -x
          oc whoami
          oc project
